/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'canvas-deep': 'var(--color-canvas-deep)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-charcoal': 'var(--color-surface-charcoal)',
        'surface-architectural': 'var(--color-surface-architectural)',
        'surface-card-frosted': 'var(--color-surface-card-frosted)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-tint': 'var(--color-surface-tint)',

        primary: 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',

        secondary: 'var(--color-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',

        tertiary: 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-tertiary-container': '#004d18',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': '#002106',
        'on-tertiary-fixed-variant': '#00531b',

        'on-background': 'var(--color-on-background)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'editorial-sage-light': 'var(--color-editorial-sage-light)',
        'editorial-sage-muted': 'var(--color-editorial-sage-muted)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'border-hairline': 'var(--color-border-hairline)',
        'border-subtle': 'var(--color-border-subtle)',

        'signal-positive': 'var(--color-signal-positive)',
        'signal-positive-subtle': 'var(--color-signal-positive-subtle)',
        'signal-advisory': 'var(--color-signal-advisory)',
        'signal-advisory-subtle': 'var(--color-signal-advisory-subtle)',
        'signal-risk': 'var(--color-signal-risk)',
        'signal-risk-subtle': 'var(--color-signal-risk-subtle)',

        error: 'var(--color-error)',
        'error-container': 'var(--color-error-container)',
        'on-error': 'var(--color-on-error)',
        'on-error-container': 'var(--color-on-error-container)',

        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'inverse-primary': 'var(--color-inverse-primary)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-DEFAULT)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      spacing: {
        gutter: 'var(--space-gutter)',
        'gutter-mobile': 'var(--space-gutter-mobile)',
        unit: '4px',
        'container-max': '1440px',
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        'space-xs': 'var(--space-xs)',
        'space-sm': 'var(--space-sm)',
        'space-md': 'var(--space-md)',
        'space-lg': 'var(--space-lg)',
        'space-xl': 'var(--space-xl)',
        'space-2xl': 'var(--space-2xl)',
        'margin-desktop': 'var(--space-margin)',
        'margin-mobile': 'var(--space-margin-mobile)',
        margin: 'var(--space-margin)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        display: ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'label-numeric': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'label-md': ['Space Grotesk', 'Noto Sans KR', 'sans-serif'],
        'body-sm': ['Geist', 'Noto Sans KR', 'sans-serif'],
        'body-md': ['Geist', 'Noto Sans KR', 'sans-serif'],
        'body-lg': ['Geist', 'Noto Sans KR', 'sans-serif'],
        sans: ['Geist', 'Noto Sans KR', 'sans-serif'],
      },
      fontSize: {
        display: ['3.75rem', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-mobile': ['2.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg': ['3.75rem', { lineHeight: '1.05', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg-mobile': ['1.875rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['1.75rem', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['0.9375rem', { lineHeight: '1.55', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['0.6875rem', { lineHeight: '1', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-numeric': ['0.875rem', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '500' }],
        'label-md': ['0.875rem', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        'level-1': '0 2px 4px rgba(0,0,0,0.25)',
        'level-2': '0 10px 15px rgba(0,0,0,0.35)',
        extrude: 'var(--shadow-extrude)',
        'extrude-sm': 'var(--shadow-extrude-sm)',
        header: 'var(--shadow-header)',
        card: 'var(--shadow-card)',
        'glow-primary': 'var(--shadow-glow-primary)',
      },
      transitionDuration: {
        tactile: '150ms',
        reveal: '420ms',
      },
    },
  },
  plugins: [],
};
