/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#001c38',
        'secondary-container': '#7db6ff',
        'tertiary-fixed': '#6ffbbe',
        'on-error-container': '#93000a',
        'surface-variant': '#d3e4fe',
        'on-secondary-container': '#00477f',
        'surface-tint': '#455f88',
        'surface-bright': '#f8f9ff',
        'on-secondary-fixed-variant': '#004881',
        'tertiary-container': '#003e28',
        surface: '#f8f9ff',
        'on-tertiary': '#ffffff',
        tertiary: '#002617',
        'secondary-fixed': '#d3e4ff',
        'secondary-fixed-dim': '#a2c9ff',
        'primary-fixed-dim': '#adc7f7',
        'error-container': '#ffdad6',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'primary-container': '#1a365d',
        'on-secondary': '#ffffff',
        'surface-container-low': '#eff4ff',
        error: '#ba1a1a',
        secondary: '#1960a3',
        'outline-variant': '#c4c6cf',
        'on-primary-container': '#86a0cd',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#00b47d',
        'on-background': '#0b1c30',
        background: '#f8f9ff',
        'primary-fixed': '#d6e3ff',
        'on-primary-fixed': '#001b3c',
        'on-surface': '#0b1c30',
        primary: '#002045',
        'on-tertiary-fixed': '#002113',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'on-primary': '#ffffff',
        'inverse-primary': '#adc7f7',
        'on-surface-variant': '#43474e',
        'inverse-surface': '#213145',
        'on-primary-fixed-variant': '#2d476f',
        'on-tertiary-fixed-variant': '#005236',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        outline: '#74777f',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'container-max': '1280px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'headline-sm': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'body-md': ['Noto Sans KR', 'sans-serif'],
        'label-md': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'body-sm': ['Noto Sans KR', 'sans-serif'],
        'headline-md': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'body-lg': ['Noto Sans KR', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'headline-lg': ['Inter', 'Noto Sans KR', 'sans-serif'],
        'display-lg': ['Inter', 'Noto Sans KR', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        sans: ['Noto Sans KR', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'level-1': '0px 2px 4px rgba(0,0,0,0.05)',
        'level-2': '0px 10px 15px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
